### ISSUE TITLE
Apresentação do projeto

### ISSUE THREAD

**Issue by JonasUliana** [jetson2/website#2]
> Pra quem está começando no **Git**, e possivelmente utilizando o **GitHub**, é sempre bom dar uma lida em boas práticas de manutenção de código, e claro, conhecer a [ferramenta](http://rogerdudler.github.io/git-guide/index.pt_BR.html).

Melhora no arquivo [**README.md**](https://github.com/jetson2/website/blob/master/README.md), apresentando melhor o projeto, afinal de contas, sem conhecer algo, não tem como contribuir 👍

**Comment by jetson2** [comment]
ok kkk
